services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory

  tests:
    build: .
    depends_on:
      - dynamodb
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      DYNAMODB_REGION: us-west-2
      DYNAMODB_VERSION: latest
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
